### ISSUE TITLE
yarn并yarn dev后报错

### ISSUE THREAD

**Issue by ajavaer** [jeasoncc/book-editor#1]
报错很多，如下图：

https://s1.ax1x.com/2022/03/12/b7jeRe.png

一次yarn用了半个小时。。
然后我windows系统运行这样报错，不甘心用mac重新clone安装，也是这样，最后用U盘装了个Ubantu安装，也是这样。。。

**Comment by ajavaer** [comment]
感谢您的开源，给您发送了微信申请没有加上

**Comment by ajavaer** [comment]
这是全部的报错内容

【腾讯文档】 
https://docs.qq.com/doc/DRnd3RVVqZlF6allB

**Comment by ajavaer** [comment]
补充几个小问题，首页右键书籍显示 编辑章节，应为 编辑书籍

书籍设置了主角后，导出为文本或者word后，都会在主角文字前后加上a标签符号，实际上不需要这个

**Comment by jeasoncc** [comment]
收到，感谢您提交的问题清单。
对于 yarn 无法安装的问题，有部分依赖需要连接外网才能下载，建议多试几次。

对于导出的问题，我后面会处理。
再次感谢您提出的宝贵意见。
